{
	"folder": null,
	"name": "Second Chance",
	"type": "feature",
	"img": "icons/magic/time/arrows-circling-pink.webp",
	"system": {
		"ac": {
			"baseFormula": "",
			"formula": "",
			"grantsDisadvantage": false,
			"maxDex": 0,
			"minStr": 0,
			"mode": 2,
			"requiresNoShield": false,
			"requiresUnarmored": false
		},
		"actions": {
			"xYFAP2i0pLj3C0Ev": {
				"name": "Second Chance",
				"activation": {
					"type": "reaction",
					"cost": 1,
					"reactionTrigger": "Friendly creature (including yourself) is suffering effects as result of a failed saving throw"
				},
				"consumers": {},
				"rolls": {},
				"prompts": {},
				"uses": {
					"value": 0,
					"max": "",
					"per": "",
					"recharge": {
						"formula": "1d6",
						"rechargeType": "custom",
						"rechargeAmount": "1",
						"threshold": 6
					}
				}
			}
		},
		"description": "<p>When a friendly creature (including yourself) is suffering effects as result of a failed saving throw, you can spend your reaction to allow it to attempt that saving throw again.</p>",
		"favorite": false,
		"secretDescription": "",
		"source": "gpg1",
		"uses": {
			"value": 0,
			"max": "",
			"per": "",
			"recharge": {
				"formula": "1d6",
				"threshold": 6
			}
		},
		"concentration": false,
		"featureType": "class",
		"grants": {},
		"prerequisite": "",
		"requiresBloodied": false,
		"schemaVersion": {
			"version": 0.019,
			"lastMigration": {
				"version": {
					"schema": 0.018,
					"foundry": "11.315",
					"system": "0.18.11"
				}
			}
		},
		"classes": ""
	},
	"effects": [],
	"flags": {},
	"_id": "24ug4h1p7cfhunpk",
	"_stats": {
		"coreVersion": "12",
		"systemId": "a5e",
		"systemVersion": "0.19.16"
	}
}